### ISSUE TITLE
微信3.9.8.25版本导出为空白

### ISSUE THREAD

**Issue by sijiniuge** [XgHao/WeChat-Contact#13]
用微信的3.9.8.25版本 导出文件里 数据为空白。是否需要降低版本才能使用呢？

**Comment by sijiniuge** [comment]
重新安装了微信 也不行，程序能运行，输出后只有 首行带有 备注 昵称 微信号 地区 标签 个性签名 元数据 的空白表格。😅 
挺尴尬的。

**Comment by XgHao** [comment]
方便的话 提供下以下信息
操作系统版本号
屏幕分辨率和缩放
![image](https://github.com/XgHao/WeChat-Contact/assets/40883019/0d204ff7-aa28-49c2-b88c-480b789126d9)

**Comment by XgHao** [comment]
试一下新的release  用管理员身份运行
