### ISSUE TITLE
微信版本3.9.10.9，导出300个之后微信提示：为了您的安全，暂时退出了。能否加入随机延迟，模拟真实点击，比如0.5s左右的一个随机数，谢谢大佬。

### ISSUE THREAD

**Issue by Ortu** [XgHao/WeChat-Contact#15]
微信版本3.9.10.9，导出300个之后微信提示：为了您的安全，暂时退出了。能否加入随机延迟，模拟真实点击，比如0.5s左右的一个随机数，谢谢大佬。

**Comment by XgHao** [comment]
是微信客户端提示的吗

**Comment by Ortu** [comment]
是的，微信客户端自动退出登录之后提示的。

XgHao ***@***.***> 于2024年5月17日周五 09:53写道：

**Comment by XgHao** [comment]
https://github.com/XgHao/WeChat-Contact/releases/tag/v3.9.10
