### ISSUE TITLE
可否增加“电话号码”字段？

### ISSUE THREAD

**Issue by Sillyli5678** [XgHao/WeChat-Contact#16]
上面那个问题遇到过，我这边再次重启微信就可以了，不过加入随机延迟何鼠标偏移是不是更象真的？我还遇到过两三次导出到半吊子就停了，不知道是不是我动了鼠标键盘啥的。

**Comment by XgHao** [comment]
我这只是模仿人去微信好友页复制粘贴的
现在微信好友页没有手机号码的字段  所以也没办法加
![image](https://github.com/XgHao/WeChat-Contact/assets/40883019/24d8442c-941f-4fa0-a3be-cde86067185b)

**Comment by Sillyli5678** [comment]
哦哦，我看到“备注”里面有“电话”的字段，还以为是在这个地方复制黏贴的咧，有没有可能模拟到这个页面下去Copy数据？
我用Power Automate试了一下，没找到提取的办法（能力不够啊），看到网络上有做到的，只是我看不到具体实现，不会做。 
>Среда, 22 мая 2024, 9:38 +08:00 от XgHao ***@***.***>:
> 
> 
>我这只是模仿人去微信好友页复制粘贴的
>现在微信好友页没有手机号码的字段 所以也没办法加
>image.png (view on web)
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <XgHao/WeChat-Contact/issues/16/2123716031 @ github . com> 
 
 
--
Silly Li
Отправлено из Почты  Mail.ru

**Comment by XgHao** [comment]
ahk 是可以拿到窗口控件句柄的  理论上只要界面上的文字都能提取 
不过还没在计划内  我初衷只是想备份一下好友列表的基础数据🤪

**Comment by Sillyli5678** [comment]
了解
目前都是用微信互换联系方式的，我都是记录在微信好友的“电话号码”字段中。
在微信中积累的蛮多的没有倒腾到手机里的，想批量导出微信的内容，再导入手机。
也就是说，我们对数据“基础”的定义不一样咯。
希望能看到在您有空有计划的时候把这个字段提取一下。
谢谢，！ 
>Понедельник, 24 июня 2024, 15:44 +08:00 от XgHao ***@***.***>:
> 
> 
>ahk 是可以拿到窗口控件句柄的 理论上只要界面上的文字都能提取
>不过还没在计划内 我初衷只是想备份一下好友列表的基础数据🤪
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <XgHao/WeChat-Contact/issues/16/2185827442 @ github . com>
 
 
--
Silly Li
Отправлено из Почты  Mail.ru

**Comment by 609293964** [comment]
+1，想微信备注的手机号，和系统通讯录同步下
