### ISSUE TITLE
导出的好友不全，我有280+好友，总是导出不到100就提示导出完成

### ISSUE THREAD

**Issue by zhaiweiwei** [XgHao/WeChat-Contact#6]

**Comment by zhaiweiwei** [comment]
<img width="660" alt="Snipaste_2023-05-28_12-27-45" src="https://github.com/XgHao/WeChat-Contact/assets/133031253/81d564e4-cb78-483b-a06c-4ff09af93148">

**Comment by zhaiweiwei** [comment]
我发现了，每次到这个用户就退出了

**Comment by XgHao** [comment]
> 我发现了，每次到这个用户就退出了

在这个用户界面 ctrl+A 全选  然后ctrl+C复制 看看复制出来的有几行数据  或者信息去敏后贴一下 我这边看戏

**Comment by XgHao** [comment]
https://github.com/XgHao/WeChat-Contact/releases/tag/v3.1.0

**Comment by zhaiweiwei** [comment]
> https://github.com/XgHao/WeChat-Contact/releases/tag/v3.1.0

不错噢，完美解决了我遇到的问题，现在能导出了，赞👍
