### ISSUE TITLE
遇到已注销的微信号联系人会停止

### ISSUE THREAD

**Issue by ydx425** [XgHao/WeChat-Contact#8]
遇到已注销微信号会停止，目前可以把已注销的联系人删除后重新导出

**Comment by XgHao** [comment]
已注销的帐号 联系人页面方便看下吗
可以的话在这个页面使用ctrl+A  ctrl+C  全选复制  贴上来  我抽空兼容下

**Comment by dgfuyou** [comment]
导出数据不全，可能是这个原因。

**Comment by XgHao** [comment]
> 导出数据不全，可能是这个原因。

注销帐号的页面方便看下吗

**Comment by ydx425** [comment]
注销的联系人已经删除了，看不到相关页面。大概就是只有一个默认头像，昵称位置显示的是“已注销”3个字。其他内容都没有
